### ISSUE TITLE
Tables with unique field who is primary

### ISSUE THREAD

**Issue by vlafranca** [cruddy/cruddy#87]
Hi,
First of all i must say cruddy is a very good way to create backend admin !
But i encounter a blocking problem actually with tables composed by a unique field who is primaryKey.

I have have to tables in this case and on each one i can not create new records : "Specified model not found", this is using field->string type, and if i use field->increments to use primary type i do not see the field in the creation form.

Thanks in advance for your help.

**Comment by lazychaser** [comment]
Hi. Not sure what are you talking about, but if you need the primary key to be visible, you need to specify this implicitly:

```php
$schema->increments('id')->hide(false);
```

**Comment by vlafranca** [comment]
Hi,
` $schema->increments('tag_name')->hide(false);`
does not show the field in the creation tab ...

How can i edit this key ?

**Comment by lazychaser** [comment]
Hm... I see that you've changed the primary key, and have you specified it in your model?

```php
class Tag extends Eloquent {

   protected $primaryKey = 'tag_name';
}
```

And also, in this case, you shouldn't use `increments` and use `string` rather (since increments is of type integer).

**Comment by vlafranca** [comment]
Hi,
All is specified correctly in the models ...
If i use `string` i get the error `Specified model not found`. But the 
grid view is loaded correctly.

Le 30/01/2015 06:50, Alexander Kalnoy a écrit :
>
> Hm... I see that you've changed the primary key, and have you 
> specified it in your model?
>
> class  Tag  extends  Eloquent  {
>
>     protected  $primaryKey  =  'tag_name';
> }
>
> And also, in this case, you shouldn't use |increments| and use 
> |string| rather (since increments is of type integer).
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cruddy/cruddy/issues/87#issuecomment-72157490>.
>



---
L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast.
http://www.avast.com

**Comment by lazychaser** [comment]
Hm... Please provide model and schema definitions.

And also, look at the `laravel.log` file and look for expanded exception info of this particular error.

**Comment by vlafranca** [comment]
Here is the model :
````
<?php
class TagModel extends \Eloquent {
	protected $fillable = ['tag_name'];

	protected $primaryKey = 'tag_name';

	protected $table = 'tags';

	public $timestamps = false;

	public function offers()
	{
		return $this->belongsToMany('OfferModel', 'pivot_offers_tags', 'tag_name', 'offer_id');
	}
}````

And here is the Schema : 
`
<?php

use Kalnoy\Cruddy\Schema\BaseSchema;
use Kalnoy\Cruddy\Service\Validation\FluentValidator;

class TagSchema extends BaseSchema {

    protected $model = 'TagModel';

    /**
     * The name of the column that is used to convert a model to a string.
     *
     * @var string
     */
    protected $titleAttribute = null;

    /**
     * The name of the column that will sort data by default.
     *
     * @var string
     */
    protected $defaultOrder = null;

    //protected $filters = ['group'];

    /**
     * Define some fields.
     *
     * @param \Kalnoy\Cruddy\Schema\Fields\InstanceFactory $schema
     */
    public function fields($schema)
    {
        $schema->string('tag_name');
    }

    /**
     * Define some columns.
     *
     * @param \Kalnoy\Cruddy\Schema\Columns\InstanceFactory $schema
     */
    public function columns($schema)
    {
        $schema->col('tag_name');
        $schema->compute('Offres liées', function($o){
            $offers = $o->offers;
            return count($offers).' - '.HTML::link(route('cruddy.index', ['offers', 'tags' => $o->tag_name]), 'Voir les offres');
        })->format('Plain');
    }

    /**
     * Define some files to upload.
     *
     * @param \Kalnoy\Cruddy\Repo\Stub $repo
     */
    public function files($repo)
    {

    }

    /**
     * Define validation rules.
     *
     * @param \Kalnoy\Cruddy\Service\Validation\FluentValidator $v
     */
    public function rules($v)
    {
        $v->always(
        [

        ]);
    }
}`

Nothing in the laravel.log about the model not found ...

Thanks a lot for your help

**Comment by lazychaser** [comment]
Tell me exactly what you do to get the error and where this error is displayed.

**Comment by vlafranca** [comment]
![sans titre](https://cloud.githubusercontent.com/assets/7658059/5988095/eea7b962-a94f-11e4-802a-34c21493d371.png)

Here is what happen when i click on create button.

**Comment by lazychaser** [comment]
Owww, I got it. That's a major bug! I'll fix it soon.

2015-01-31 15:49 GMT+03:00 vlafranca <notifications@github.com>:

> [image: sans titre]
> <https://cloud.githubusercontent.com/assets/7658059/5988095/eea7b962-a94f-11e4-802a-34c21493d371.png>
>
> Here is what happen when i click on create button.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/cruddy/cruddy/issues/87#issuecomment-72316509>.
>



-- 
Best regards, Alexander Kalnoy.

**Comment by vlafranca** [comment]
Thanks a lot !

What is the cause ?

**Comment by lazychaser** [comment]
Backbone works the way when the model has primary key specified it treats
it as it is exists already and tries to update it rather than create.

Also, be careful with changing primary key since It might brake things and
also note that you can only use alphanumeric values, no spaces and such.
31 ñÎ× 2015 Ç. 17:18 ÐÏÌØÚÏ×ÁÔÅÌØ "vlafranca" <notifications@github.com>
ÎÁÐÉÓÁÌ:

**Comment by vlafranca** [comment]
Why if using the creation form it tries to update the row ? I think it is a very strange behaviour ... and if the key already exist it should throw an error instead of trying to update. The update form is already present, don't you think ?

Also, how can i add more characters  ? As my primary key is not restrected to this.

**Comment by lazychaser** [comment]
Why cant you use common auto incremented id column? Id and value. You cant
use other characters because primary key is used in routing. It also should
be unique.
31 ñÎ× 2015 Ç. 18:05 ÐÏÌØÚÏ×ÁÔÅÌØ "vlafranca" <notifications@github.com>
ÎÁÐÉÓÁÌ:

**Comment by vlafranca** [comment]
I'm totally agree with you but let me explain you my case :
I use a Tag table, like a tag on linkedin or any site, a tag is unique, 
so why does it need an auto increment field in more ? it's just wasting 
performance in a useless int ID.


Le 31/01/2015 19:13, Alexander Kalnoy a écrit :
> Why cant you use common auto incremented id column? Id and value. You 
> cant
> use other characters because primary key is used in routing. It also 
> should
> be unique.
> 31 ñÎ× 2015 Ç. 18:05 ÐÏÌØÚÏ×ÁÔÅÌØ "vlafranca" <notifications@github.com>
> ÎÁÐÉÓÁÌ:
>
> > Why if using the creation form it tries to update the row ? I think 
> it is
> > a very strange behaviour ... and if the key already exist it should 
> throw
> > an error instead of trying to update. The update form is already 
> present,
> > don't you think ?
> >
> > Also, how can i add more characters ? As my primary key is not 
> restrected
> > to this.
> >
> > --
> > Reply to this email directly or view it on GitHub
> > <https://github.com/cruddy/cruddy/issues/87#issuecomment-72321124>.
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cruddy/cruddy/issues/87#issuecomment-72328910>.
>



---
L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast.
http://www.avast.com

**Comment by lazychaser** [comment]
Because i believe that integer indexes are faster :) i havent really tested
text like keys, tell me what youll get in result
31 Янв 2015 г. 21:24 пользователь "vlafranca" <notifications@github.com>
написал:

**Comment by vlafranca** [comment]
Indeed I haven't thought about indexes but in case of Tags or Categories 
for example performances are not affected because of very low amount of 
records.

Anyway when will you fix the update/create issue ? it will fit my needs 
anyway.

Le 31/01/2015 19:28, Alexander Kalnoy a écrit :
> Because i believe that integer indexes are faster :) i havent really 
> tested
> text like keys, tell me what youll get in result
> 31 Янв 2015 г. 21:24 пользователь "vlafranca" <notifications@github.com>
> написал:
>
> > I'm totally agree with you but let me explain you my case :
> > I use a Tag table, like a tag on linkedin or any site, a tag is unique,
> > so why does it need an auto increment field in more ? it's just wasting
> > performance in a useless int ID.
> >
> >
> > Le 31/01/2015 19:13, Alexander Kalnoy a écrit :
> > > Why cant you use common auto incremented id column? Id and value. You
> > > cant
> > > use other characters because primary key is used in routing. It also
> > > should
> > > be unique.
> > > 31 ñÎ× 2015 Ç. 18:05 ÐÏÌØÚÏ×ÁÔÅÌØ "vlafranca" 
> <notifications@github.com>
> > > ÎÁÐÉÓÁÌ:
> > >
> > > > Why if using the creation form it tries to update the row ? I think
> > > it is
> > > > a very strange behaviour ... and if the key already exist it should
> > > throw
> > > > an error instead of trying to update. The update form is already
> > > present,
> > > > don't you think ?
> > > >
> > > > Also, how can i add more characters ? As my primary key is not
> > > restrected
> > > > to this.
> > > >
> > > > --
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/cruddy/cruddy/issues/87#issuecomment-72321124>.
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/cruddy/cruddy/issues/87#issuecomment-72328910>.
> > >
> >
> >
> >
> > ---
> > L'absence de virus dans ce courrier électronique a été vérifiée par le
> > logiciel antivirus Avast.
> > http://www.avast.com
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/cruddy/cruddy/issues/87#issuecomment-72329319>.
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cruddy/cruddy/issues/87#issuecomment-72329512>.
>



---
L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast.
http://www.avast.com

**Comment by lazychaser** [comment]
I already fixed your issue besides those text keys, i dont know how they
will work
 31 Янв 2015 г. 21:31 пользователь "vlafranca" <notifications@github.com>
написал:

**Comment by vlafranca** [comment]
Hi,
I just tryed your fix, but i'm still having the same error ... It seems the backbone still try to update the key instead of creating it ...

**Comment by lazychaser** [comment]
Have you updated the assets?

**Comment by vlafranca** [comment]
yes, i've made : php artisan asset:publish kalnoy/cruddy

**Comment by lazychaser** [comment]
You sure that your version constraint is something like `~0.4.0`? I've just checked and everything works fine on my test app. Try hard refresh in browser. If nothing works, provide request info from browser when you hit create.

**Comment by vlafranca** [comment]
Here is my composer.json :

"require-dev": {
    "kalnoy/cruddy":"~0.4.0"
},


composer update gives this :
  - Removing kalnoy/cruddy (dev-master f854527)
   - Installing kalnoy/cruddy (v0.4.0)
     Loading from cache

Request still returning this :

 1. error:"Specified model not found."
 2.

Le 02/02/2015 16:05, Alexander Kalnoy a écrit :
>
> You sure that your version constraint is something like |~0.4.0|? I've 
> just checked and everything works fine on my test app. Try hard 
> refresh in browser. If nothing works, provide request info from 
> browser when you hit create.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cruddy/cruddy/issues/87#issuecomment-72471693>.
>



---
L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast.
http://www.avast.com

**Comment by lazychaser** [comment]
Wow, just checked out and noticed that packagist didn't update the package and no new version was available. You can update the package now.

**Comment by vlafranca** [comment]
Yeah working fine now !

Thanks
